#!/usr/bin/env python3
"""
LuCI Snort3 Module - Installation Script Generator
Generates install.sh by embedding src/ files directly (offline install).
For the online (wget/curl) variant, use install.sh directly.
"""

import os
import sys

# Source -> destination mappings for the ucode/JS layout
FILE_MAPPINGS = {
    'src/ucode/snort.uc':                                              '/usr/share/rpcd/ucode/snort',
    'src/rpcd/snort.json':                                             '/usr/share/rpcd/acl.d/luci-app-snort.json',
    'src/root/usr/share/luci/menu.d/luci-app-snort.json':             '/usr/share/luci/menu.d/luci-app-snort.json',
    'src/htdocs/luci-static/resources/view/snort/config.js':          '/www/luci-static/resources/view/snort/config.js',
    'src/htdocs/luci-static/resources/view/snort/status.js':          '/www/luci-static/resources/view/snort/status.js',
    'src/htdocs/luci-static/resources/view/snort/alerts.js':          '/www/luci-static/resources/view/snort/alerts.js',
    'src/htdocs/luci-static/resources/view/snort/log.js':             '/www/luci-static/resources/view/snort/log.js',
    'src/etc/init.d/snort':                                            '/etc/init.d/snort',
    'src/i18n/snort.en.po':                                            '/usr/share/luci/i18n/snort.en.po',
    'src/i18n/snort.fr.po':                                            '/usr/share/luci/i18n/snort.fr.po',
}

EXECUTABLE = {'/etc/init.d/snort'}

HEADER = '''#!/bin/sh
# LuCI Snort3 - Offline Installation Script (auto-generated)
# Generated by generate_install.py
# All source files are embedded inline — no internet access needed.

set -e

GREEN='\\033[0;32m'
RED='\\033[0;31m'
YELLOW='\\033[1;33m'
NC='\\033[0m'

[ "$(id -u)" -eq 0 ] || { echo "${RED}Must run as root${NC}"; exit 1; }
command -v snort >/dev/null 2>&1 || { echo "${RED}snort3 not installed${NC}"; exit 1; }

mkdir -p /usr/share/rpcd/ucode \\
         /usr/share/rpcd/acl.d \\
         /usr/share/luci/menu.d \\
         /www/luci-static/resources/view/snort \\
         /etc/snort \\
         /var/log

'''

FOOTER = '''
# Reload
/etc/init.d/rpcd restart
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache 2>/dev/null

# UCI defaults
[ -f /etc/config/snort ] || cat > /etc/config/snort << 'UCIEOF'
config snort 'snort'
\toption enabled '0'
\toption interface ''
\toption mode 'ids'
\toption method 'afpacket'
\toption home_net '192.168.0.0/24'
\toption config_dir '/etc/snort'
\toption rules_dir '/etc/snort/rules'
\toption log_dir '/var/log'
\toption log_alerts '1'
\toption log_format 'fast'
\toption ruleset 'community'
UCIEOF

echo "${GREEN}Installation complete! Navigate to Services → Snort IDS/IPS${NC}"
'''


def embed_file(src_path, dst_path):
    if not os.path.exists(src_path):
        print(f'WARNING: {src_path} not found, skipping', file=sys.stderr)
        return ''

    with open(src_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Escape single quotes for sh heredoc
    escaped = content.replace("'", "'\"'\"'")
    chmod = f'chmod +x {dst_path}\n' if dst_path in EXECUTABLE else ''

    return (
        f"# --- {src_path} ---\n"
        f"cat > '{dst_path}' << 'HEREDOC_{dst_path.replace('/','_').strip('_')}'\n"
        f"{content}"
        f"HEREDOC_{dst_path.replace('/','_').strip('_')}\n"
        f"{chmod}"
        f"echo \"Installed {dst_path}\"\n\n"
    )


def main():
    out = HEADER
    for src, dst in FILE_MAPPINGS.items():
        out += embed_file(src, dst)
    out += FOOTER

    output_file = 'install_offline.sh'
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(out)
    os.chmod(output_file, 0o755)
    print(f'Generated {output_file}')


if __name__ == '__main__':
    main()
